# Generated by Django 5.0.4 on 2024-05-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.URLField(),
        ),
    ]
