# Generated by Django 5.0.4 on 2024-05-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_cover_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
